 
 2022-01-22 17:10:21,376 - error
Traceback (most recent call last):
  File "D:\bridgelabz\python\address_book\services\operations.py", line 29, in get_user_choice
    option = int(input("Press \n 1) Add new Address Book \n 2) Edit Existing book "
ValueError: invalid literal for int() with base 10: 'asd'
 
 2022-01-22 17:11:51,293 - error
Traceback (most recent call last):
  File "D:\bridgelabz\python\address_book\services\operations.py", line 29, in get_user_choice
    option = int(input("Press \n 1) Add new Address Book \n 2) Edit Existing book "
ValueError: invalid literal for int() with base 10: 'asdf'
 
 2022-01-22 17:12:43,533 - error
Traceback (most recent call last):
  File "D:\bridgelabz\python\address_book\services\operations.py", line 29, in get_user_choice
    option = int(input("Press \n 1) Add new Address Book \n 2) Edit Existing book "
ValueError: invalid literal for int() with base 10: 'asd'
